### ISSUE TITLE
Not compitable with react-boilerplate

### ISSUE THREAD

**Issue by Muditr93** [merodriguezblanco/react-transformicons#2]
Whenever we import react-transformicons, it throws out an error -->
the  Module parse failed: Unexpected token (6:4)
You may need an appropriate loader to handle this file type.

![screen shot 2018-05-18 at 6 27 56 pm](https://user-images.githubusercontent.com/24772048/40235984-a94803a2-5ac9-11e8-8572-40c840dc7650.png)

**Comment by iamsaksham** [comment]
I encountered the same whenever I try to import anything from `react-transformicons`.
Is there any compatibility issue with react versions?
@merodriguezblanco

**Comment by merodriguezblanco** [comment]
Hi @Muditr93 @iamsaksham thanks for reporting this. I never got the time to come back to the loader!

Please feel free to submit a PR with a fix :)

**Comment by iamsaksham** [comment]
hi @merodriguezblanco , thanks a lot for such a ready reply. We are looking into this, we'll submit a PR as soon as we fix this.

**Comment by iamsaksham** [comment]
Created a pull request #3 please consider merging it. @merodriguezblanco let me know if any modifications are required in the pull request.

**Comment by iamsaksham** [comment]
@merodriguezblanco Please consider merging the pull request #3 .

**Comment by iamsaksham** [comment]
Resolved with PR #3
